# This file configures the analyzer to use the lint rule set from `package:lint`
include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude: [build/**]
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
linter:
  rules:
    public_member_api_docs: false
