final headingRegex = RegExp("^#{1,6}");
final boldRegex = RegExp(r'(\*\*|__)(.*?)\1');
final italicRegex = RegExp(r'(\*|_)(.*?)\1');
final boldItalicRegex = RegExp(r'(\*\*\*|___)(.*?)\1');
final unorderedListRegex = RegExp(r'^[-*]\s');
final orderListRegex = RegExp(r'^\d+\.\s');
final taskListRegex = RegExp(r'^- \[([ xX])\](.*)$');
final strikethroughRegex = RegExp('~~(.*?)~~');
final imageRegex = RegExp(r'!\[(.*?)\]\((.*?)\)');
final linkRegex = RegExp(r'\[(.*?)\]\((.*?)\)');
final urlRegex = RegExp(r'^https?:\/\/[^\s]+$');
final highlightRegex = RegExp('==(.*?)==');
final subscriptRegex = RegExp('~(.*?)~');
final superscriptRegex = RegExp(r'\^(.*?)\^');
final horizontalRuleRegex = RegExp(r'^\s*([-*_]){3,}\s*$');
final emojiRegex = RegExp(':([a-zA-Z0-9_]+):');
