final headingRegex = RegExp("^#{1,6}");
final boldRegex = RegExp(r'(\*\*|__)(.*?)\1');
final italicRegex = RegExp(r'(\*|_)(.*?)\1');
final boldItalicRegex = RegExp(r'(\*\*\*|___)(.*?)\1');
final unorderedListRegex = RegExp('^[-*] ');
final orderListRegex = RegExp(r'^\d+\.\s');
final taskListRegex = RegExp(r'^- \[([ xX])\] (.*)$');
final strikethroughRegex = RegExp('~~(.*?)~~');
final imageRegex = RegExp(r'!\[(.*?)\]\((.*?)\)');
final linkRegex = RegExp(r'\[(.*?)\]\((.*?)\)');
final highlightRegex = RegExp('==(.*?)==');
