name: my_flutter_package
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Very good coverage
        uses: VeryGoodOpenSource/very_good_coverage@v3.0.0

      # - name: Dart package workflow
      #   uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/dart_package.yml@v1

      # - name: Flutter package workflow
      #   uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1

      # - name: Ensure semantic PRs
      #   uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/semantic_pull_request.yml@v1

      # - name: Verify package scores on pub.dev
      #   uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/pana.yml@v1

      # - name: Run spell check
      #   uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/spell_check.yml@v1

      # - name: Publish Flutter package
      #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      #   uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_pub_publish.yml@v1

      # - name: Publish Dart package
      #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      #   uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/dart_pub_publish.yml@v1

      # - name: Publish Mason bricks
      #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      #   uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/mason_publish.yml@v1

      # - name: License check
      #   uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/license_check.yml@v1
